name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test:prod

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
